server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002 #eureka服务端名称
  client:
    register-with-eureka: false #是否向eureka服务中心注册自己
    fetch-registry: false #false 自己是服务中心
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/


